version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: family_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_segura
      MYSQL_DATABASE: smart_family_db
      MYSQL_USER: admin_family
      MYSQL_PASSWORD: user_password_segura
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: